# Generated by Django 2.0.3 on 2018-04-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='mod_num',
            field=models.IntegerField(default=0),
        ),
    ]
